"""Generate MCPGuard-compatible security policies from AIShield scan results.

Converts AIShield findings into MCPGuard YAML configuration that can
be used to block vulnerable tools, enforce rate limits, and prevent
known attack vectors discovered during fine-tuning security scanning.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from aishield.scanner import ScanResult, Severity

MCPGUARD_TEMPLATE = """# MCPGuard Policy — Auto-generated by AIShield
# Source: {source}
# Scan ID: {scan_id}
# Generated: {timestamp}

mode: http
listen_host: 127.0.0.1
listen_port: 8080
target_url: {target_url}

# Rate limiting
rate_limit: {rate_limit}
rate_window: 60

# Blocking rules
block_on_injection: true
block_on_poisoning: true

# Security rules
allow:
{allow_list}

deny:
{deny_list}

# Hot-reload config
# hot_reload: true
"""


def generate_mcpguard_policy(
    result: ScanResult,
    target_url: str = "http://localhost:8000",
    rate_limit: int = 100,
) -> str:
    """Generate an MCPGuard-compatible YAML policy from scan results.

    Analyzes findings and generates allow/deny rules for MCPGuard
    based on detected vulnerable tools, malicious adapters, and
    pipeline risks.

    Args:
        result: AIShield ScanResult.
        target_url: Target MCP server URL.
        rate_limit: Max requests per rate window.

    Returns:
        YAML policy string suitable for MCPGuard.
    """
    allow_tools: set[str] = _get_known_safe_tools()
    deny_tools: set[str] = set()

    for finding in result.findings:
        _process_finding(finding, deny_tools)

    allow_list = "\n".join(f"  - {tool}" for tool in sorted(allow_tools))
    deny_list = "\n".join(f"  - {tool}" for tool in sorted(deny_tools))

    return MCPGUARD_TEMPLATE.format(
        source=result.target,
        scan_id=result.scan_id,
        timestamp=result.timestamp,
        target_url=target_url,
        rate_limit=_compute_rate_limit(result, rate_limit),
        allow_list=allow_list if allow_list else "  # No safe tools identified",
        deny_list=deny_list if deny_list else "  # No malicious tools identified",
    )


def save_mcpguard_policy(
    result: ScanResult,
    output_path: str | Path,
    target_url: str = "http://localhost:8000",
    rate_limit: int = 100,
) -> Path:
    """Generate and save an MCPGuard policy to file.

    Args:
        result: AIShield ScanResult.
        output_path: Path to save the policy YAML.
        target_url: Target MCP server URL.
        rate_limit: Max requests per rate window.

    Returns:
        Path to the saved policy file.
    """
    policy = generate_mcpguard_policy(result, target_url, rate_limit)
    path = Path(output_path)
    path.write_text(policy)
    return path


def _get_known_safe_tools() -> set[str]:
    """Return default safe tool list."""
    return {
        "get_weather",
        "search_web",
        "read_file",
        "get_time",
        "calculate",
        "translate",
        "summarize",
    }


def _process_finding(
    finding: Any,
    deny_tools: set[str],
) -> None:
    """Process a single finding to update allow/deny tool lists."""
    check = finding.check.lower() if hasattr(finding, "check") else ""
    detail = finding.detail.lower() if hasattr(finding, "detail") else ""
    sev = finding.severity if hasattr(finding, "severity") else Severity.MEDIUM

    # Critical/high findings about tools should be denied
    if sev in (Severity.CRITICAL, Severity.HIGH):
        _deny_matching_tools(check, detail, deny_tools)

    # LoRA findings that modify target modules
    if "lora" in check or "suspicious modules" in detail:
        for mod in _extract_modules(detail):
            deny_tools.add(mod)

    # Pipeline findings about unsafe operations
    if "exec" in check or "subprocess" in detail:
        deny_tools.add("exec")
        deny_tools.add("shell")
        deny_tools.add("bash")
        deny_tools.add("sudo")


def _deny_matching_tools(check: str, detail: str, deny_tools: set[str]) -> None:
    """Add tools to deny list based on finding content."""
    tool_keywords = {
        "exec": ["exec", "run", "execute", "shell"],
        "write_file": ["write_file", "save_file", "create_file"],
        "delete": ["delete", "remove", "drop_"],
        "network": ["network", "curl", "wget", "http_request"],
        "database": ["query", "sql", "db_"],
    }

    text = f"{check} {detail}"
    for tool, keywords in tool_keywords.items():
        if any(kw in text for kw in keywords):
            deny_tools.add(tool)


def _extract_modules(detail: str) -> list[str]:
    """Extract tool/module names from finding detail."""
    modules = re.findall(r"(?:lm_head|embed_tokens|embed_positions|final_layer_norm)", detail)
    # Also extract comma-separated module names
    if not modules and "target_modules" in detail:
        parts = re.split(r"[:\s,]+", detail)
        modules = [
            p for p in parts if p.endswith("_proj") or p.endswith("_head") or p.endswith("_norm")
        ]
    return modules


def _compute_rate_limit(result: ScanResult, default: int = 100) -> int:
    """Compute appropriate rate limit based on risk score."""
    risk = result.risk_score
    if risk >= 80:
        return max(10, default // 5)
    if risk >= 50:
        return max(20, default // 3)
    if risk >= 20:
        return max(50, default // 2)
    return default
